name: "ChatGPT Action"
description: "Review or Summarize your PR with AI"
branding:
  icon: activity
  color: green

inputs:
  number:
    description: "ID of Pull Request or Issue"
    required: true
  apiKey:
    description: "Your ChatGPT apiKey token."
    required: true
  mode:
    description: "Mode"
    required: true
    default: "pr"
  split:
    description: "Should I split the prompt and how to split it?"
    required: true
    default: "yolo"
  operation:
    description: "Review or Summarize the PR?"
    required: true
    default: "review"
outputs:
  comment:
    description: "The comment from chatgpt."
runs:
  using: "node16"
  main: "dist/index.js"
